### ISSUE TITLE
aaa请问JavaScript部分的贪吃蛇你做出来来了吗qaq，我跟着敲但是效果跟他不一样qaq

### ISSUE THREAD

**Issue by zbbBella** [sunmiao0301/MIT-6.148-Web-Lab#1]

**Comment by sunmiao0301** [comment]
如果跟着敲没做出来的话，可以：
1、拉取这个仓库：https://github.com/weblab-workshops/catbook-react
2、切换分支：git checkout w1-complete 拿到可正确运行的版本，可以看看和你跟着敲的版本有什么不一样

**Comment by zbbBella** [comment]
恩恩，好的！！谢谢！！！！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Miao ***@***.***&gt;; 
发送时间: 2022年3月30日(星期三) 晚上6:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sunmiao0301/MIT-6.148-Web-Lab] aaa请问JavaScript部分的贪吃蛇你做出来来了吗qaq，我跟着敲但是效果跟他不一样qaq (Issue #1)





 
如果跟着敲没做出来的话，可以：
 1、拉取这个仓库：https://github.com/weblab-workshops/catbook-react
 2、切换分支：git checkout w1-complete 拿到可正确运行的版本，可以看看和你跟着敲的版本有什么不一样

**Comment by sunmiao0301** [comment]
:sunglasses:
